[package]
name = "pingpong_server"
version = "0.1.0"
authors = ["kilometers <kilo@meters.sh>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4"
serde_json = "1"
serde = { version = "1", features = ["derive"] }